# Generated by Django 5.0 on 2023-12-16 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.TextField()),
                ('author', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('subscription_date', models.DateField(auto_now_add=True)),
                ('emails_sent_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_start_date', models.DateField()),
                ('year_end_date', models.DateField()),
                ('emails_sent_this_year', models.IntegerField(default=0)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailsender.subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='QuotesSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailsender.quote')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailsender.subscriber')),
            ],
            options={
                'unique_together': {('quote', 'subscriber')},
            },
        ),
    ]
